### ISSUE TITLE
Section 'gcode_shell_command update_git_script' is not a valid config section

### ISSUE THREAD

**Issue by bino277** [CasperVerswijvelt/CR6-SE-Klipper-Config#1]
Section 'gcode_shell_command update_git_script' is not a valid config section

**Comment by CasperVerswijvelt** [comment]
I use [KIAUH's gcode_shell_command extension](https://github.com/dw-0/kiauh/blob/master/docs/gcode_shell_command.md)

Note that this is a backup repository for my config files
I suggest using [KoenVanDuffel](https://github.com/KoenVanduffel)'s repository [here](https://github.com/KoenVanduffel/CR-6_Klipper) as a baseline, it is also what I started from.
